# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ruc_dir": "ers_codes.ipynb",
         "ui_dir": "ers_codes.ipynb",
         "ruca_dir": "ers_codes.ipynb",
         "download_and_combine_ruc": "ers_codes.ipynb",
         "download_and_combine_ui": "ers_codes.ipynb",
         "download_and_combine_ruca": "ers_codes.ipynb",
         "download_and_combine_all": "ers_codes.ipynb",
         "get_ruc_df": "ers_codes.ipynb",
         "get_ui_df": "ers_codes.ipynb",
         "get_ruca_df": "ers_codes.ipynb",
         "memory": "rurality.ipynb",
         "prepare_outside_ua_df": "rurality.ipynb",
         "nearest_gridpoint": "rurality.ipynb",
         "prepare_ui_df": "rurality.ipynb",
         "prepare_ruc_df": "rurality.ipynb",
         "prepare_ruca_df": "rurality.ipynb",
         "gen_rural_hrsa": "rurality.ipynb",
         "get_hrsa_rural_in_cbsa": "rurality.ipynb",
         "get_far_df": "rurality.ipynb",
         "add_rural_cols": "rurality.ipynb",
         "build_parquet_dataset": "rurality.ipynb",
         "get_df": "rurality.ipynb",
         "download_file": "util.ipynb",
         "tag_invalid_values": "util.ipynb",
         "validate_values": "util.ipynb",
         "init": "geo_gazetteer.ipynb",
         "download_data": "geo_gazetteer.ipynb",
         "build_state_data": "geo_gazetteer.ipynb",
         "data": "geo_gazetteer.ipynb",
         "get_mapping": "geo_gazetteer.ipynb",
         "PATH": "ers_codes.ipynb"}

modules = ["ers_codes.py",
           "rurality.py",
           "ui.py",
           "util.py",
           "geo_gazetteer.py"]

doc_url = "https://antonbabkin.github.io/rurec/"

git_url = "https://github.com/antonbabkin/rurec/tree/master/"

def custom_doc_links(name): return None
