# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ruc_dir": "ers_codes.ipynb",
         "ui_dir": "ers_codes.ipynb",
         "ruca_dir": "ers_codes.ipynb",
         "download_and_combine_ruc": "ers_codes.ipynb",
         "download_and_combine_ui": "ers_codes.ipynb",
         "download_and_combine_ruca": "ers_codes.ipynb",
         "download_and_combine_all": "ers_codes.ipynb",
         "get_ruc_df": "ers_codes.ipynb",
         "get_ui_df": "ers_codes.ipynb",
         "get_ruca_df": "ers_codes.ipynb",
         "abs_path": "resources.ipynb",
         "Resource": "resources.ipynb",
         "Registry": "resources.ipynb",
         "pull": "resources.ipynb",
         "push": "resources.ipynb",
         "paths": "resources.ipynb",
         "add": "resources.ipynb",
         "get": "resources.ipynb",
         "remove": "resources.ipynb",
         "download_file": "util.ipynb"}

modules = ["ers_codes.py",
           "resources.py",
           "util.py"]

doc_url = "https://antonbabkin.github.io/rurec"

git_url = "https://github.com/antonbabkin/rurec/tree/master/"

def custom_doc_links(name): return None
