# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ruc_dir": "ers_codes.ipynb",
         "ui_dir": "ers_codes.ipynb",
         "ruca_dir": "ers_codes.ipynb",
         "download_and_combine_ruc": "ers_codes.ipynb",
         "download_and_combine_ui": "ers_codes.ipynb",
         "download_and_combine_ruca": "ers_codes.ipynb",
         "download_and_combine_all": "ers_codes.ipynb",
         "get_ruc_df": "ers_codes.ipynb",
         "get_ui_df": "ers_codes.ipynb",
         "get_ruca_df": "ers_codes.ipynb",
         "memory": "infogroup.ipynb",
         "data_years": "infogroup.ipynb",
         "convert_schema": "infogroup.ipynb",
         "get_schema": "infogroup.ipynb",
         "pad_with_zeroes": "infogroup.ipynb",
         "validate_raw_strings": "infogroup.ipynb",
         "convert_dtypes": "infogroup.ipynb",
         "validate_raw_numbers": "infogroup.ipynb",
         "replace_invalid": "infogroup.ipynb",
         "load_validate_convert": "infogroup.ipynb",
         "build_parquet_dataset": "infogroup.ipynb",
         "shared_cols": "infogroup.ipynb",
         "get_df": "infogroup.ipynb",
         "describe_variable": "infogroup.ipynb",
         "style": "infogroup.ipynb",
         "Paths": "resources.ipynb",
         "paths": "resources.ipynb",
         "Resource": "resources.ipynb",
         "Registry": "resources.ipynb",
         "pull": "resources.ipynb",
         "push": "resources.ipynb",
         "registry": "resources.ipynb",
         "add": "resources.ipynb",
         "get": "resources.ipynb",
         "remove": "resources.ipynb",
         "download_file": "util.ipynb",
         "tag_invalid_values": "util.ipynb",
         "validate_values": "util.ipynb"}

modules = ["ers_codes.py",
           "infogroup.py",
           "resources.py",
           "ui.py",
           "util.py"]

doc_url = "https://antonbabkin.github.io/rurec/"

git_url = "https://github.com/antonbabkin/rurec/tree/master/"

def custom_doc_links(name): return None
