# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/resources.ipynb (unless otherwise specified).

__all__ = ['paths']

# Cell
from pathlib import Path
import configparser

# Cell
def _get_root_dir():
    """Return `pathlib.Path` to project root directory.
    Root is identified by presence of "settings.ini" file."""
    d = Path.cwd()
    while d != d.parent:
        if (d / 'settings.ini').exists(): return d
        d = d.parent
    raise Exception(f'Can not find project root at or above "{Path.cwd()}"')

# Cell
def _get_paths_from_config():
    root = _get_root_dir()
    config = configparser.ConfigParser()
    config.read(root / 'settings.ini')

    def get_abs_path(path_key):
        path = Path(config['resources'][path_key])
        if not path.is_absolute():
            path = root / path
        return path

    paths = dict()
    paths['root'] = root
    paths['tmp'] = get_abs_path('temp_dir')
    paths['ers_codes'] = get_abs_path('ers_codes_dir')
    return paths

paths = _get_paths_from_config()