# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/nbs/rurality.ipynb (unless otherwise specified).

__all__ = ['get_df']

# Cell
import json

import numpy as np
import pandas as pd
import fastparquet

from rurec import resources
from .resources import Resource
from rurec import infogroup
from rurec import ers_codes

# Cell
def get_df(year, cols=None):
    """Return one year of InfoGroup with rurality variables.
    Subset of columns can be loaded by passing list to `cols`.
    """
    res = resources.get(f'infogroup/rural/{year}')
    return pd.read_parquet(res.path, 'fastparquet', columns=cols)