# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/nbs/ui.ipynb (unless otherwise specified).

__all__ = []

# Cell
if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Perform tasks within Rural Economy project.')
    parser.add_argument('task', help='chose a task', choices=['build_parquet'])
    args = parser.parse_args()
    if args.task == 'build_parquet':
        from rurec import infogroup
        infogroup.build_parquet_dataset(21)
        print(args.task, 'finished')