# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/util.ipynb (unless otherwise specified).

__all__ = ['download_file']

# Cell
from pathlib import Path
from urllib.parse import urlparse, unquote

import requests

# Cell
def download_file(url, dir=None, fname=None, overwrite=False):
    """Download file from given `url` and put it into `dir`.
    Current working directory is used as default. Missing directories are created.
    File name from `url` is used as default.
    Return absolute pathlib.Path of the downloaded file."""

    if dir is None:
        dir = '.'
    dpath = Path(dir).resolve()
    dpath.mkdir(parents=True, exist_ok=True)

    if fname is None:
        fname = Path(urlparse(url).path).name
    fpath = dpath / fname

    if not overwrite and fpath.exists():
        print(f'File {fname} already exists.')
        return fpath

    with requests.get(url) as r:
        r.raise_for_status()
        with open(fpath, 'wb') as f:
            f.write(r.content)

    print(f'Downloaded file {fname}.')
    return fpath