name: rurec
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - jupyterlab>=3
  - nbdime
  - ipywidgets
  - requests
  - matplotlib
  - pandas
  - openpyxl # new .xlsx format
  - xlrd # old .xls format
  - geopandas
