name: rurec
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - ipython
  - matplotlib
  - pandas
  - pandas-gbq
  - geopandas
  - jupyter
  - jupyterlab
  - nbdime
  - pip:
    - google-cloud-bigquery
