name: rurec
channels:
  - defaults
  - conda-forge
dependencies:
  - numba
  - python>=3.6
  - ipython
  - matplotlib
  - pandas
  - pandas-gbq
  - geopandas
  - jupyter
  - jupyterlab
  - nbdime
  - pip:
    - scipy
    - sympy
    - quilt
    - google-cloud-bigquery
    - quantecon
    - sphinxcontrib-jupyter
