name: rurec
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - jupyterlab
  - jupytext
  - ipywidgets
  - requests
  - matplotlib
  - pandas
  - openpyxl # new .xlsx format
  - xlrd # old .xls format
  - geopandas
  - pyarrow # parquet for geopandas
  - python-graphviz # option visualization of NAICS concordances
  - lxml
  - psutil
  
