name: rurec
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - requests
  - jupyterlab
  - matplotlib
  - pandas
  - xlrd
#   - geopandas>=0.4
#   - pip:
#     - google-cloud-storage
