project:
  type: website
  render:
    - index.ipynb
    - rurality.ipynb
    - io_for_dummies.Rmd
    - toy_story.Rmd
  post-render: touch _site/.nojekyll

website:
  title: "Rural Economy"
  navbar:
    background: primary
    left:
      - href: index.ipynb
        text: Home
      - href: rurality.ipynb
        text: Rurality
      - io_for_dummies.Rmd
      - toy_story.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



