---
title: "InfoGroup County aggregates"
format: html
---

County aggregation of InfoGroup data

```{r}
library(tidyverse)
library(arrow)
library(glue)
library(logger)

proj_path <- rprojroot::find_rstudio_root_file

source(proj_path("rurec/reseng.R"), local = (reseng <- new.env()))

PATH = list(
  raw = "~/work/data/infogroup/{year}_Business_Academic_QCQ.csv.gz",
  agg = proj_path("data/infogroup/county_naics_{year}.rds")
)

log_threshold("DEBUG")
```



```{r}
county_naics_sum <- reseng$cache(function(year) {
  
  d <- read_csv(
    glue(PATH$raw), 
    col_types = cols_only(
      `State` = "c",
      `County Code` = "c", 
      `Primary NAICS Code` = "c", 
      `Employee Size (5) - Location` = "i", 
      `Sales Volume (9) - Location` = "i"
    )
  ) %>%
    rename(
      st = `State`,
      cty = `County Code`, 
      naics = `Primary NAICS Code`, 
      emp = `Employee Size (5) - Location`, 
      sales = `Sales Volume (9) - Location`
    ) %>%
    mutate(naics = str_sub(naics, 1, 6))
  
  state_codes <- c("AL" ~ "01", "AK" ~ "02", "AZ" ~ "04", "AR" ~ "05", "CA" ~ "06", "CO" ~ "08", "CT" ~ "09", "DE" ~ "10", "DC" ~ "11", "FL" ~ "12", "GA" ~ "13", "HI" ~ "15", "ID" ~ "16", "IL" ~ "17", "IN" ~ "18", "IA" ~ "19", "KS" ~ "20", "KY" ~ "21", "LA" ~ "22", "ME" ~ "23", "MD" ~ "24", "MA" ~ "25", "MI" ~ "26", "MN" ~ "27", "MS" ~ "28", "MO" ~ "29", "MT" ~ "30", "NE" ~ "31", "NV" ~ "32", "NH" ~ "33", "NJ" ~ "34", "NM" ~ "35", "NY" ~ "36", "NC" ~ "37", "ND" ~ "38", "OH" ~ "39", "OK" ~ "40", "OR" ~ "41", "PA" ~ "42", "RI" ~ "44", "SC" ~ "45", "SD" ~ "46", "TN" ~ "47", "TX" ~ "48", "UT" ~ "49", "VT" ~ "50", "VA" ~ "51", "WA" ~ "53", "WV" ~ "54", "WI" ~ "55", "WY" ~ "56", "AS" ~ "60", "GU" ~ "66", "MP" ~ "69", "PR" ~ "72", "VI" ~ "78")
  
 d %>%
  group_by(st, cty, naics) %>%
  summarize(across(everything(), ~ sum(.x, na.rm = TRUE)), .groups = "drop") %>%
  mutate(st = case_match(st, !!!state_codes)) 
}, PATH$agg)

```

```{r}
log_tictoc("starting")
for (y in 1997:2017) {
  t <- county_naics_sum(y)
  log_tictoc("finished ", y)
}
```


